name: Jekyll site CI
<html lang="en">
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
<link href="file:///C:/Users/leonardo/Downloads/templatemo_590_topic_listing/templatemo_590_topic_listing/topics-detail.html" rel="stylesheet">
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"
